### ISSUE TITLE
connect to test database but you cannot explain why we want test database in doc

### ISSUE THREAD

**Issue by akshayvinchurkar** [vsan21/MapJourney#1]
connect to test database but you cannot explain why we want test database in doc

```
const connection = mysql.createConnection({
  host: 'localhost',
  user: 'root',
  password: `${MYSQL_KEY}`,
  database: 'test'
})

connection.connect((err) => {
  if(err) throw err;
  console.log('You are now connected to the database...');

  var person = {name: 'Larry', age: 41, email: 'larrybird@gmail.com'};
  connection.query('INSERT INTO people SET ?', person, (err, results, fields) => {
    if(err) throw err; 
  })
})
```

why we need test database? and this route still gives me error /yelp/results cannot get

**Comment by vsan21** [comment]
Hey Akshay! I was making a dummy database to test out the connection. I am close to getting all the features finished to grab real user data so I will make sure to update this file soon 🙂

**Comment by vsan21** [comment]
bash scripts now contains the correct database, and project MVP is complete

**Comment by akshayvinchurkar** [comment]
![error](https://user-images.githubusercontent.com/10510889/41451927-fa6e1fe0-708c-11e8-91d8-b3d21715476a.PNG)
